# TYPE 1 #

trigger: none

pool: mera-agent-pool

jobs:

  # >>> Terraform basic commands . . .
- job: terraforminitial
  displayName: Terrform basic commands
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
  
  - task: TerraformTask@5
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'

  # >>> Scanning Job . . . 
- job: Scanning
  dependsOn: terraforminitial
  displayName: Scanning Job
  steps:

  # tfsec main scan
  - task: tfsec@1
    inputs:
      version: 'v1.26.0'
      debug: true
      dir: '$(System.DefaultWorkingDirectory)'
  condition: succeededOrFailed()   # <-- Report will always publish even if tfsec fails or pass


  # >>> Manual Validation Job . . . 
- job: validation
  dependsOn: Scanning
  displayName: Manual Validation
  pool: server
  steps:
  - task: ManualValidation@1
    displayName: Requesting approver
    inputs:
      notifyUsers: 'bisht.amit08@gmail.com'
      approvers: 'bisht.amit08@gmail.com'
      instructions: 'Kingly approve the pipeline'

- job: Terraformapply
  dependsOn: validation
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'
