trigger: none

pool: mera-agent-pool

jobs:
- job: build
  displayName: Initialising
  steps:
  - task: PowerShell@2
    displayName: Terraform Fetch Directory
    inputs:
      targetType: 'inline'
      script: |
        echo "Working directory check"

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'

  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'


- job: scan
  dependsOn: build
  displayName: Planning
  steps:
  # - task: TerraformTask@5
  #   displayName: Terraform Init
  #   inputs:
  #     provider: 'azurerm'
  #     command: 'init'
  #     workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
  #     backendServiceArm: 'new-service'
  #     backendAzureRmStorageAccountName: 'stglactab'
  #     backendAzureRmContainerName: 'cntrlab'
  #     backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Plan
    inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
        environmentServiceNameAzureRM: 'new-service'

    

