trigger: none

pool: mera-agent-pool

jobs:
- job: terraforminitial
  displayName: Terrform basic commands
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
  
  - task: TerraformTask@5
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'


- job: Scanning
  dependsOn: terraforminitial
  displayName: Scanning Job
  steps:
  - task: tfsec@1
    displayName: Scanning the code
    inputs:
      version: 'v1.26.0'
      debug: true
      dir: '$(System.DefaultWorkingDirectory)'
    
  - task: PowerShell@2
    displayName: "Run tfsec (JUnit output)"
    inputs:
      targetType: 'inline'
      script: |
        tfsec --format junit --out tfsec-report.xml .

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'tfsec-report.xml'
      testResultsFormat: 'JUnit'
      mergeTestResults: true


- job: validation
  dependsOn: Scanning
  displayName: Manual Validation
  pool: server
  steps:
  - task: ManualValidation@1
    displayName: Requesting approver
    inputs:
      notifyUsers: 'bisht.amit08@gmail.com'
      approvers: 'bisht.amit08@gmail.com'
      instructions: 'Kingly approve the pipeline'


- job: terraformapply
  dependsOn: validation
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'
