trigger: none

pool: mera-agent-pool

jobs:

  # >>> Terraform basic commands . . .
- job: terraforminitial
  displayName: Terrform basic commands
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
  
  - task: TerraformTask@5
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'


  # >>> Scanning Job . . . 
- job: Scanning
  dependsOn: terraforminitial
  displayName: Scanning Job
  steps:

  # 0) Install tfsec CLI on Windows
  - powershell: |
      Invoke-WebRequest -Uri "https://github.com/aquasecurity/tfsec/releases/download/v1.26.0/tfsec-windows-amd64.exe" -OutFile "tfsec.exe"
      Move-Item -Path "tfsec.exe" -Destination "C:\tfsec.exe" -Force
      echo "##vso[task.prependpath]C:\"
    displayName: "Install tfsec CLI (Windows)"
    continueOnError: true

  # 1) tfsec extension scan
  - task: tfsec@1
    displayName: Scanning the code
    inputs:
      version: 'v1.26.0'
      debug: true
      dir: '$(System.DefaultWorkingDirectory)'
    continueOnError: true

  # 2) Create JUnit report
  - powershell: |
      tfsec --format junit --out tfsec-report.xml "$(System.DefaultWorkingDirectory)"
    displayName: "Run tfsec (JUnit output)"
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    continueOnError: true

  # 3) Publish report
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/tfsec-report.xml'
      testResultsFormat: 'JUnit'
      mergeTestResults: true
    condition: succeededOrFailed()



  # >>> Manual Validation Job . . . 
- job: validation
  dependsOn: Scanning
  displayName: Manual Validation
  pool: server
  steps:
  - task: ManualValidation@1
    displayName: Requesting approver
    inputs:
      notifyUsers: 'bisht.amit08@gmail.com'
      approvers: 'bisht.amit08@gmail.com'
      instructions: 'Kingly approve the pipeline'


- job: terraformapply
  dependsOn: validation
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'
