trigger: none

pool: mera-agent-pool

jobs:

  # >>> Terraform basic commands . . .
- job: terraforminitial
  displayName: Terrform basic commands
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
  
  - task: TerraformTask@5
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'


  # >>> Scanning Job . . . 
- job: Scanning
  dependsOn: terraforminitial
  displayName: Scanning Job
  steps:

  # 0) Install tfsec CLI (FOR WINDOWS AGENT)
  - task: PowerShell@2
    displayName: "Install tfsec CLI (Windows)"
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Downloading tfsec CLI for Windows..."
        Invoke-WebRequest -Uri "https://github.com/aquasecurity/tfsec/releases/download/v1.26.0/tfsec-windows-amd64.exe" -OutFile "$(System.DefaultWorkingDirectory)\tfsec.exe"
        Write-Host "tfsec downloaded. Adding to PATH..."
        Write-Host "##vso[task.prependpath]$(System.DefaultWorkingDirectory)"
    continueOnError: true


  # 1) Run tfsec extension scan
  - task: tfsec@1
    displayName: "Scanning the code"
    inputs:
      version: 'v1.26.0'
      debug: true
      dir: '$(System.DefaultWorkingDirectory)'
    continueOnError: true


  # 2) Generate JUnit XML report using tfsec CLI
  - task: PowerShell@2
    displayName: "Run tfsec (JUnit output)"
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Running tfsec CLI to generate JUnit report..."
        tfsec --format junit --out tfsec-report.xml "$(System.DefaultWorkingDirectory)"
      workingDirectory: "$(System.DefaultWorkingDirectory)"
    continueOnError: true


  # 3) Publish XML report to Azure DevOps Test Results
  - task: PublishTestResults@2
    displayName: "Publish tfsec Test Results"
    inputs:
      testResultsFiles: '**/tfsec-report.xml'
      testResultsFormat: 'JUnit'
      mergeTestResults: true
    condition: succeededOrFailed()


  # >>> Manual Validation Job . . . 
- job: validation
  dependsOn: Scanning
  displayName: Manual Validation
  pool: server
  steps:
  - task: ManualValidation@1
    displayName: Requesting approver
    inputs:
      notifyUsers: 'bisht.amit08@gmail.com'
      approvers: 'bisht.amit08@gmail.com'
      instructions: 'Kingly approve the pipeline'


- job: terraformapply
  dependsOn: validation
  steps:
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      backendServiceArm: 'new-service'
      backendAzureRmStorageAccountName: 'stglactab'
      backendAzureRmContainerName: 'cntrlab'
      backendAzureRmKey: 'basic.tfstate'

  - task: TerraformTask@5
    displayName: Terraform Apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
      environmentServiceNameAzureRM: 'new-service'
